#!/bin/bash

USAGE="$0 [-s|--src SOURCE DIR] <[-d|--dst DESTINATION DIR]|[-y|--year YEAR]>"

## Defaults
SRC=meeting_data/processed/current
DST_BASE=meeting_data/processed
DST=

## Arg parse
while [[ $# -gt 0 ]]; do
    case $1 in
        -s|--src)
            SRC=$2
            shift ## past argument
            shift ## past value
            ;;
        -d|--dst)
            DST=$1
            shift ## past argument
            shift ## past value
            ;;
        -y|--year)
            YEAR=$2
            shift ## past argument
            shift ## past value
            ;;
        -*|--*)
            echo "Unknown option $1"
            echo $USAGE
            exit 1
        ;;
        *)
            echo "Unknown argument $1"
            echo $USAGE
            exit 1
    esac
done

## Make destination
if [[ ! -z $YEAR ]]; then
    if [[ ! -z $DST ]]; then
        echo "--dst and --year are mutually exclusive optioins"
        echo $USAGE
        exit 1
    fi
    DST="$DST_BASE/$YEAR"
fi

if [[ -z $DST ]]; then
    echo "One of --dst or --year required"
    echo $USAGE
    exit 1
fi

echo "Using SRC=$SRC"
echo "Using DST=$DST"

for FILE in `ls "$SRC"`; do
    if [[ -f "$SRC/$FILE" ]] && [[ -f "$DST/$FILE" ]]; then
        echo "$SRC/$FILE >> $DST/$FILE"
        tail -n +2 "$SRC/$FILE" >> "$DST/$FILE"
    fi
done
